spring:
  application:
    name: api-gateway
    cloud:
        config:
            enable: true
            import-check:
                enabled: true

server:
  port: 8765

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

auth:
  introspection:
    enabled: false
    url: http://localhost:8081/api/auth/introspect

security:
  jwt:
    secret-key: 036e0ce585032470454dc6ece4e78ac74918d56b70774ae7d1fd45ca0725ac4a
    expiration-time: 36000000
#logging:
#  level:
#    root: debug
