server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/user_details}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-migration-naming: true

  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE:2MB}
      max-request-size: ${MAX_REQUEST_SIZE:2MB}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:idhanushd17@gmail.com}
    password: ${MAIL_PASSWORD:qcjm acxg perq urdp}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    serverUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
    prefer-ip-address: true

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:036e0ce585032470454dc6ece4e78ac74918d56b70774ae7d1fd45ca0725ac4a}
    expiration-time: ${JWT_EXPIRATION_TIME:36000000}
