server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/user_details
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-migration-naming: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: idhanushd17@gmail.com
    password: qcjm acxg perq urdp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

security:
  jwt:
    secret-key: 036e0ce585032470454dc6ece4e78ac74918d56b70774ae7d1fd45ca0725ac4a
    expiration-time: 36000000